name: Documentation Issue
description: File an issue against the public documentation.
title: "[Docs]: "
labels: documentation
assignees:
  - AndrewDiMola
body:
  - type: input
    id: source
    attributes:
      label: Documentation URL
      description: Please provide the link to the <a href="https://developer.grammarly.com/docs/">documentation</a> page.
    validations:
      required: false
  - type: textarea
    id: happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: What did you expect to happen?
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: markdown
    attributes:
      value: "__Thank you for helping us improve our documentation!__"
